version: '3'

services:
  soundboard-channel-points:
    container_name: soundboard-channel-points
    build:
      context: .
      dockerfile: Dockerfile
    image: soundboard-channel-points
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 9000:9000
    volumes:
      - ./public:/usr/src/public
      - ./.config:/usr/src/.config
      - ./sound-effects:/usr/src/sound-effects
    depends_on:
      - tts
    networks:
      - soundboard

  tts:
    container_name: mozilla-tts
    image: synesthesiam/mozillatts:en
    networks:
      - soundboard
    # TTS engine uses enormous amount of RAM. When started, it uses about 500 MiB.
    # However, https://github.com/synesthesiam/docker-mozillatts stated that
    # 1GB of RAM or more is needed to load larger models.
    mem_limit: 768M

networks:
  soundboard:
    name: soundboard-network
